//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojKatalog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbKatalogEntities : DbContext
    {
        public dbKatalogEntities()
            : base("name=dbKatalogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Katalozi> Katalozi { get; set; }
        public virtual DbSet<Kategorii> Kategorii { get; set; }
        public virtual DbSet<Klienti> Klienti { get; set; }
        public virtual DbSet<Kompanii> Kompanii { get; set; }
        public virtual DbSet<Poedineci> Poedineci { get; set; }
        public virtual DbSet<Poraki> Poraki { get; set; }
        public virtual DbSet<Proizvodi> Proizvodi { get; set; }
    }
}
