//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojKatalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Katalozi
    {
        public Katalozi()
        {
            this.Kategorii = new HashSet<Kategorii>();
        }
    
        public int IdKatalozi { get; set; }
        public string NazivNaKatalog { get; set; }
        public string OpisNaKatalog { get; set; }
        public Nullable<System.DateTime> DataNaKreiranje { get; set; }
        public Nullable<int> IdPoedinci { get; set; }
        public Nullable<int> IdKompanii { get; set; }
    
        public virtual Kompanii Kompanii { get; set; }
        public virtual Poedineci Poedineci { get; set; }
        public virtual ICollection<Kategorii> Kategorii { get; set; }
        public virtual WebSiteSettings WebSiteSettings { get; set; }
    }
}
