//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojKatalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorii
    {
        public Kategorii()
        {
            this.Kategorii1 = new HashSet<Kategorii>();
            this.Proizvodi = new HashSet<Proizvodi>();
        }
    
        public int IdKategorii { get; set; }
        public string NazivNaKategorija { get; set; }
        public Nullable<int> RoditelId { get; set; }
        public Nullable<int> IdKatalozi { get; set; }
    
        public virtual Katalozi Katalozi { get; set; }
        public virtual ICollection<Kategorii> Kategorii1 { get; set; }
        public virtual Kategorii Kategorii2 { get; set; }
        public virtual ICollection<Proizvodi> Proizvodi { get; set; }
    }
}
