//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojKatalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kompanii
    {
        public Kompanii()
        {
            this.Katalozi = new HashSet<Katalozi>();
            this.Klienti = new HashSet<Klienti>();
        }
    
        public int IdKompanii { get; set; }
        public string NazivNaKompanija { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public string Mail { get; set; }
        public string LogoNaKompanija { get; set; }
        public string OpisNaKompanija { get; set; }
        public string Telefon { get; set; }
    
        public virtual ICollection<Katalozi> Katalozi { get; set; }
        public virtual ICollection<Klienti> Klienti { get; set; }
    }
}
