//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojKatalog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Kompanii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kompanii()
        {
            this.Katalozi = new HashSet<Katalozi>();
            this.Poraki = new HashSet<Poraki>();
            this.Klienti = new HashSet<Klienti>();
        }
    
        public int IdKompanii { get; set; }
        [DisplayName("Компанија")]
        public string NazivNaKompanija { get; set; }
        [DisplayName("Корисничко име")]
        public string KorisnickoIme { get; set; }
        [DisplayName("Лозинка")]
        public string Lozinka { get; set; }
        [DisplayName("Мејл")]
        public string Mail { get; set; }
        [DisplayName("Лого")]
        public string LogoNaKompanija { get; set; }
        [DisplayName("Опис")]
        public string OpisNaKompanija { get; set; }
        [DisplayName("Телефон")]
        public string Telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Katalozi> Katalozi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poraki> Poraki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klienti> Klienti { get; set; }
    }
}
