//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojKatalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poedineci
    {
        public Poedineci()
        {
            this.Klienti = new HashSet<Klienti>();
            this.Katalozi = new HashSet<Katalozi>();
        }
    
        public int IdPoedineci { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
    
        public virtual ICollection<Klienti> Klienti { get; set; }
        public virtual ICollection<Katalozi> Katalozi { get; set; }
    }
}
