//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojKatalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poraki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poraki()
        {
            this.Klienti = new HashSet<Klienti>();
        }
    
        public int IdPoraki { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IdKompanii { get; set; }
        public Nullable<int> IdPoedinci { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public string SenderMail { get; set; }
    
        public virtual Kompanii Kompanii { get; set; }
        public virtual Poedinci Poedinci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klienti> Klienti { get; set; }
    }
}
