//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojKatalog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Proizvodi
    {
        public int IdProizvodi { get; set; }
        [DisplayName("Назив")]
        public string NazivNaProizvod { get; set; }
        [DisplayName("Спецификација")]
        public string Specifikacija { get; set; }
        [DisplayName("Цена")]
        public Nullable<decimal> Cena { get; set; }
        [DisplayName("Попуст")]
        public Nullable<int> Popust { get; set; }
        [DisplayName("Слика")]
        public string SlikaNaProizvod { get; set; }
        [DisplayName("Достапност")]
        public Nullable<bool> Dostapnost { get; set; }
        public Nullable<int> IdKategorii { get; set; }
    
        public virtual Kategorii Kategorii { get; set; }
    }
}
